name: Deploy to EC2 on Push to Main
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build production
        run: pnpm run build

      - name: create deployment package
        run: |
          tar -czf deployment-package.tar.gz dist

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "deployment-package.tar.gz"
          target: "~/react-app/"

      - name: Serve Dist and Cleanup
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/react-app
            tar -xzf deployment-package.tar.gz
            rm -rf deployment-package.tar.gz
            pm2 serve dist 80 --name "react-app" --spa --no-daemon
